### PR TITLE
Add cli flag :apple:

### LINKED ISSUE #16: Generated `*.scss.d.ts` files should retain the original class names
The fix is to pass in the `--nameFormat none` [CLI flag](https://github.com/skovy/typed-scss-modules#--nameformat--n) when invoking `tsm` (`typed-scss-modules`) at: https://github.com/yuanqing/create-figma-plugin/blob/dacd1b226f8c8558a9db0eb827a5160b3ee4d95b/packages/build/src/build-scss-modules-typings.ts#L17-L24

### PR DESCRIPTION
**Pull request by weilinzung**
closes #16 

@yuanqing Would be better to include the contribute doc, like how to run locally and test locally.

### CODE REVIEW

**Comment by weilinzung** [comment]
@yuanqing ??

**Comment by weilinzung** [comment]
@yuanqing  this is not released yet, right?

**Comment by yuanqing** [comment]
This fix is in `0.0.80`

**Comment by yuanqing** [comment]
Also added a script with [instructions for testing locally](https://github.com/yuanqing/create-figma-plugin/blob/9403ca435bc38d86f3920aa8a060c2a784aa0173/docs/contributing.md) – hope this helps!

**Pull request merged**
